### ISSUE TITLE
Drive or network connection that the shortcut 'pdf-viewer.ink' refers to is unavailable

### ISSUE THREAD

**Issue by Liedo** [nbbrd/jdemetra-nowcasting#10]
(from R.B.)
When I update the nowcasting model in JDemetra and look at the news, I get this error ‘problem with shortcut PDF-viewer.Ink’

![newsError](https://user-images.githubusercontent.com/13660698/58470953-1a90cd00-8143-11e9-9999-db9f672eb641.png)

I can dismiss the error message by clicking OK and everything that I need still seems to work at this point, but I just wanted to see if there is something I could do about this error

![newsBlurred](https://user-images.githubusercontent.com/13660698/58470718-98a0a400-8142-11e9-8960-8142b78202aa.png)

**Comment by maggima** [comment]
There's a bug in the Java file chooser when there's a shortcut having its link broken (due to target file deletion or the network/disk path not being available)

See : https://bugs.java.com/bugdatabase/view_bug.do?bug_id=5049016

So simply resolve the shortcut link or delete it (in that case **PDF-viewer.Ink**)
